### ISSUE TITLE
Server requires listening IP

### ISSUE THREAD

**Issue by nottisa** [HamzLDN/RemoteDesktop#15]
In a perfect world the server.py file would not require the ip to be in it at all. (localhost or other) It would just have a server and allow people to connect no matter what the ip configuration on the server side is.

**Comment by HamzLDN** [comment]
So whats the issue you are facing?

**Comment by nottisa** [comment]
It's more of a suggestion, less of an issue. Essentially the server shouldn't have to have any configuration besides port number. I'm not 100% sure if this is a you thing or a library thing as I've never used python web sockets.

**Comment by nottisa** [comment]
I figured it out, pass an empty string to the server socket in order to allow all connections. `RemoteDesktop("", 443).start_server()`
