### ISSUE TITLE
i get this once i try to use it

### ISSUE THREAD

**Issue by radialheat1** [HamzLDN/RemoteDesktop#2]
Traceback (most recent call last):
  File "client.py", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'

**Comment by matheus-lougen** [comment]
radialheat1 , have you installed the pip requirements ?
try running `pip install -r requirements.txt` on the project folder and see if the error stops

**Comment by HamzLDN** [comment]
> Traceback (most recent call last): File "client.py", line 1, in ModuleNotFoundError: No module named 'cv2'

Hey there. Sorry for the issue with the requirements.txt file. I will fix it.
A quick fix would be to do the following:
pip install opencv-python
pip install pillow
pip install pyautogui
pip install pywin32
pip install pynput

I hope that helps.

**Comment by HamzLDN** [comment]
> radialheat1 , have you installed the pip requirements ? try running `pip install -r requirements.txt` on the project folder and see if the error stops

Yeah I just realised. I will fix it ASAP. But if you cant get your code to work run these commands on the terminal.
pip install opencv-python
pip install pillow
pip install pyautogui
pip install pywin32
pip install pynput

I hope that fixes the issue :)
